services:
    backend:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./uploads:/app/uploads
        depends_on:
            - db

    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: rby6014vtziqaRwF4VEINxfnaxtrIZCaX5
            POSTGRES_DB: photosdb
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
